name: Build Plugin - Production

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: production
          path: dist
